### ISSUE TITLE
what's the "L  M  Q  H" meaning?

### ISSUE THREAD

**Issue by naoyeye** [alexeyten/qr-image#1]
`ec_level — error correction level. One of L, M, Q, H. Default M.`

L = Large? Low?
M = Middle?
Q = ?
H = High?

**Comment by braveltd** [comment]
unresolved question. What Q means there??

**Comment by alexeyten** [comment]
@braveltd 

Low
Medium
Quartile
High

**Comment by rubystar0512** [comment]
Thanks
