### ISSUE TITLE
Incompatible PNG when running on Raspberry Pi (ARMv6)

### ISSUE THREAD

**Issue by anders94** [alexeyten/qr-image#13]
When running this on X86 Linux or X86 Mac:

```
var qr = require('qr-image');
var fs = require('fs');
var readable = qr.image('hi', {type: 'png', size: 1});
var writable = fs.createWriteStream('qr.png');
readable.pipe(writable);
```

I get good images.

However, when running on a Raspberry Pi (ARMv6) I get an invalid PNG file.

Here's a hex dump of the invalid PNG:

```
89504E47 0D0A1A0A 0000000D 49484452 0000001D 0000001D 08000000 00FFFFFF 
FE000000 80494441 5478DAC5 525B0EC0 3008E2FE 97665914 C5CDF46F 593F9A5A 
7C800A9E 0EBE4511 271E6D09 95E38DB5 5517E21F 89033BCA 03CA3D56 3EDCEA26 
4B28EFE0 DCF2F277 EA65798F B78A14A9 B826A1E0 A3C2B444 156A9908 3E515120 
CD9A1473 1A9B5EF5 D107E3BD C2166B95 0D7BCD08 2794A597 5C7763D5 8BDE8E67 
AF7ED8F6 0B896C64 B8000005 75000000 0049454E 44AE4260 82
```

Here's a hex dump of the good PNG:

```
89504E47 0D0A1A0A 0000000D 49484452 0000001D 0000001D 08000000 0073F838 
D3000000 80494441 5478DAC5 525B0EC0 3008E2FE 97665914 C5CDF46F 593F9A5A 
7C800A9E 0EBE4511 271E6D09 95E38DB5 5517E21F 89033BCA 03CA3D56 3EDCEA26 
4B28EFE0 DCF2F277 EA65798F B78A14A9 B826A1E0 A3C2B444 156A9908 3E515120 
CD9A1473 1A9B5EF5 D107E3BD C2166B95 0D7BCD08 2794A597 5C7763D5 8BDE8E67 
AF7ED8F6 0B896C64 B8974AAE 14000000 0049454E 44AE4260 82
```

The header looks good but it goes off the rails around the 00FFFFFF at the end of the top line.

Possibly some sort of big-endian / little-endian issue?

node version: v0.11.11-pre

**Comment by bosson** [comment]
Hi, this patch assumes node with global "process" and breaks web use. 
The lib/crc32.js fix should test for process... pollyfilling in a process global causes confusion on a different level thats harder to manage. 

if (process.arch === 'arm') {
    module.exports = require('./crc32buffer');
    return;
}

like 

if (process && process.arch === 'arm') { ...

**Comment by alexeyten** [comment]
I'm going to get rid of this patch in new version. It was 4 years and several major versions of node ago, and I hope there is no need for it now.
