### ISSUE TITLE
Can I get a base64 encoded png?

### ISSUE THREAD

**Issue by venkatramachandran** [alexeyten/qr-image#16]
Is there an option to generate a base64 encoding of a generated png?

**Comment by timkrins** [comment]
Here is an example of encoding the result as a string to be used in a browser.

    var qr = require('qr-image');
    
    var qr_svg = qr.imageSync('string goes here', { type: 'png' });
    var qr_str = "data:image/png;base64," + qr_svg.toString('base64');
    
    console.log(qr_str);

**Comment by rstudner** [comment]
@timkrins I'm doing it, with speakeasy, and the image I get is "never valid"  (i mean, it shows up, but in google authenticator it is ALWAYS providing the wrong 6 digit code)
