### ISSUE TITLE
Can I include email, phone number, ... into one QR image?

### ISSUE THREAD

**Issue by truonguit2010** [alexeyten/qr-image#17]
Hi,
Can I include email, phone number, ... into one QR image? How to format the text to achieve that?

Thanks,

**Comment by alexeyten** [comment]
You could include any information.  See https://github.com/zxing/zxing/wiki/Barcode-Contents

**Comment by truonguit2010** [comment]
Hi, can you give me an example:
I have an email address: test@gmail.com and witesite: test.com
What the text should be? 
I tried: http://www.test.com;mailto:test@gmail.com
But It only recognize the website. Can you give me the format of the text for multi values? Thank you.

**Comment by alexeyten** [comment]
QR code just contains some text information. Ut's up to QR-reader to interpret that information. In your case I guess you nedd vCard format.

**Comment by jschulenklopper** [comment]
In vCard format, you could encode this text as/in a QR Code:
```
BEGIN:VCARD
VERSION:4.0
EMAIL:example@gmail.com
ORG:ACME
TEL:1 234 56789
URL;type=pref:http://www.example.com
END:VCARD
```
