### ISSUE TITLE
Size option not working for SVG

### ISSUE THREAD

**Issue by qawemlilo** [alexeyten/qr-image#19]
Hi, I'm trying to generate an SVG image that I can embed onto a pdf document but the size option is not working. Please check the code below.

```javascript
var qrImage = require('qr-image');

var svgObject = qrImage.svgObject('my data here', { 
  type: 'svg',
  size: 200 // width should be 200px
}); 
```
It seems the only way to change size is by changing the `ec_level` option. Any idea how I can fix this?

**Comment by qawemlilo** [comment]
Was able to scale the SVG path within my pdf document 

```javascript
doc.path(QR.path)
  .scale(QR.path / desiredSize)
  .fill();
```

**Comment by alexeyten** [comment]
Size is _size of one module (square) in pixels_, not size of whole image. The size of image depends on text length and error correction level.
