### ISSUE TITLE
Logo within qr code image

### ISSUE THREAD

**Issue by kvaillant** [alexeyten/qr-image#20]
Hi, 
Thanks a lot for your node module. Is there a way to include a logo ?

**Comment by iamkarlson** [comment]
Hello, could you implement this? It's very important feature..

**Comment by alexeyten** [comment]
That was one of main reasons to write this module in first place. Here is example: https://disk.yandex.net/qr/?text=https%3A%2F%2Fyadi.sk%2Fd%2FaPqJNaOwuQ56

There is a way, but quite strange. You could pass function as `customize` option. It will get image in some internal intermediate format that could be modified before generating final png.

There is no documentation (yet), you could look into source:

https://github.com/alexeyten/qr-image/blob/master/lib/qr.js#L71
https://github.com/alexeyten/qr-image/blob/master/lib/png.js#L63

**Comment by kvaillant** [comment]
Thanks for this answer.

Actually, I use the svg format generation. I'm not used to manipulating svg object. Maybe, you may advice me some nodejs module to manipulate svg so that I can insert a logo in.

**Comment by alexeyten** [comment]
SVG is simple text (XML) so you could use anything that works with XML. For simple tasks you could threat it as a text.

**Comment by kvaillant** [comment]
Alright, in fact, it doesn't seem to be complicated to manipulate svg and insert logo image.
Thanks. I'm closing this issue.

**Comment by zhangyaochun** [comment]
@alexeyten  is there any doc for using customize as options. I am planing to make a qr-image with logo

**Comment by hendrawd** [comment]
It has been 2 years elapsed, isn't there no documentation yet?

**Comment by alexeyten** [comment]
@hendrawd I've added an example for PNG customization.
See https://github.com/alexeyten/qr-image/blob/master/examples/customize.js
and resulting image https://github.com/alexeyten/qr-image/blob/master/examples/custom.png

**Comment by hendrawd** [comment]
Thank you for the example @alexeyten , i have tried it and it's works. But if i specify size parameter, like `size: 15` the resulting image will not be like the example. 
![custom](https://cloud.githubusercontent.com/assets/9481791/24029284/93c85922-0b07-11e7-93c4-c508f7a86764.png)

Anyway i got the idea already, about how it works.

**Comment by alexeyten** [comment]
`size` parameter is a size of one module (in pixels).
`bitmap` in `customize` function is a final image with margins etc. It could be any size depending on what you encode, with what ec level and, of course what size of module you use.

**Comment by hendrawd** [comment]
@alexeyten could you give more example how to load my png logo as a decimal pixel values, so i can modify the barcode with the pixel values?

Here is the far that i can achieve:
```javascript
var image = qr.imageSync(
    text,
    {
        type: 'png',
        ec_level: 'H',
        size: 15,
        margin: 3,
        customize: customize
    }
);

var customize = function (bitmap) {
    var size = bitmap.size;
    var data = bitmap.data;

    var margin = Math.floor(size / 2.5);

    for (var x = margin; x < size - margin; x++) {
        for (var y = margin; y < size - margin; y++) {
            var offset = coord2offset(x, y, size);
            data[offset] = 0; // this should changed with logo's pixel
        }
    }
};
```
And here is the result image:
![kuda](https://cloud.githubusercontent.com/assets/9481791/25485651/d7c8f9a0-2b88-11e7-91fb-7bd60f6b2fa0.png)

**Comment by alexeyten** [comment]
> how to load my png logo as a decimal pixel values

It's out of scope of this library. You could use [PNG.js](https://github.com/arian/pngjs) or any other library that could read PNG.

**Comment by tzechienchu** [comment]
Try this one.
https://www.npmjs.com/package/qrcode-logo

**Comment by xuqinggang** [comment]
@alexeyten  could you give me source code what you did on https://disk.yandex.net/qr/?text=https%3A%2F%2Fyadi.sk%2Fd%2FaPqJNaOwuQ56

**Comment by SorinC6** [comment]
> > how to load my png logo as a decimal pixel values
> 
> It's out of scope of this library. You could use [PNG.js](https://github.com/arian/pngjs) or any other library that could read PNG.



> @alexeyten could you give more example how to load my png logo as a decimal pixel values, so i can modify the barcode with the pixel values?
> 
> Here is the far that i can achieve:
> 
> ```js
> var image = qr.imageSync(
>     text,
>     {
>         type: 'png',
>         ec_level: 'H',
>         size: 15,
>         margin: 3,
>         customize: customize
>     }
> );
> 
> var customize = function (bitmap) {
>     var size = bitmap.size;
>     var data = bitmap.data;
> 
>     var margin = Math.floor(size / 2.5);
> 
>     for (var x = margin; x < size - margin; x++) {
>         for (var y = margin; y < size - margin; y++) {
>             var offset = coord2offset(x, y, size);
>             data[offset] = 0; // this should changed with logo's pixel
>         }
>     }
> };
> 
> function coord2offset(x, y, size) {
>     return (size + 1) * y + x + 1;
> }
> ```
> 
> And here is the result image:
> ![kuda](https://cloud.githubusercontent.com/assets/9481791/25485651/d7c8f9a0-2b88-11e7-91fb-7bd60f6b2fa0.png)



> @alexeyten could you give more example how to load my png logo as a decimal pixel values, so i can modify the barcode with the pixel values?
> 
> Here is the far that i can achieve:
> 
> ```js
> var image = qr.imageSync(
>     text,
>     {
>         type: 'png',
>         ec_level: 'H',
>         size: 15,
>         margin: 3,
>         customize: customize
>     }
> );
> 
> var customize = function (bitmap) {
>     var size = bitmap.size;
>     var data = bitmap.data;
> 
>     var margin = Math.floor(size / 2.5);
> 
>     for (var x = margin; x < size - margin; x++) {
>         for (var y = margin; y < size - margin; y++) {
>             var offset = coord2offset(x, y, size);
>             data[offset] = 0; // this should changed with logo's pixel
>         }
>     }
> };
> 
> function coord2offset(x, y, size) {
>     return (size + 1) * y + x + 1;
> }
> ```
> 
> And here is the result image:
> ![kuda](https://cloud.githubusercontent.com/assets/9481791/25485651/d7c8f9a0-2b88-11e7-91fb-7bd60f6b2fa0.png)

Hi @hendrawd , I'm in a similar situation relating with adding the logo, did you mange to get the logo to show ?
