### ISSUE TITLE
QR code with transparent background and specific color

### ISSUE THREAD

**Issue by akanass** [alexeyten/qr-image#21]
Hello,

I've a question. It's possible to generate a `qr code` with transparent background and with specific color like `white` by exemple and not `black`?

Thanks in advance for your response and if it's not possible, can you implement it?

Best regards

**Comment by alexeyten** [comment]
I prefer to keep module simple.

You could get raw matrix data and generate image with `node-png` or any other module you like.

**Comment by diosney** [comment]
+1

This would be really useful, for example, it will allow melding in credential generation.

**Comment by resteinbock** [comment]
+1

It would be very useful to supply a logo to embed in the QR code.

**Comment by lucdetellis** [comment]
+1 for transparent background option. Beyond that I agree with keeping it simple.

**Comment by bockoblur** [comment]
For people who need transparent background in codes: all vector formats are created with transparent backgrounds as it is. You can create svg code and then rasterize it if you insist on having png file.

I need the opposite thing: non-transparent backgrounds in vector formats. And maybe also custom colors for code itself.

I am willing to create a pull request and give it a shot at those two things. I would be concentrating on vector modules first (for selfish reasons - I need this), and maybe later I'll give it a shot for png...

**Comment by bockoblur** [comment]
@alexeyten , I created a fork [here](https://github.com/bockoblur/qr-image) that accepts two more options (for vector formats): `color` and `background`. Please check it out when you have the time and let me know if this is something you would merge. If not, I will publish it on `npm` as it is. Someone may find it useful.  Thank you.

**Comment by bockoblur** [comment]
A word of caution: my fork mentioned above uses indexed color PNG instead of grayscale, so if you use customization function to alter the bitmap it will not work as expected. For all other formats there are no breaking changes.

**Comment by bockoblur** [comment]
I created a pull request #52 with these modifications.
@alexeyten please review.
