### ISSUE TITLE
qr-image with href

### ISSUE THREAD

**Issue by kevkha** [alexeyten/qr-image#22]
I want to add qr-image with href so user can click on it but svg has so many double quotes so it's not working. What is the best way to print svg qrcode in this case?

Example:
```javascript
var svg_img = qr.imageSync('http://www.gizmo.com/link/', { type: 'svg' });
$("#qrdiv").html('<a href="http://www.gizmo.com/link/" target="_blank"><img src="'+svg_img+'"/></a>');
```

**Comment by kevkha** [comment]
I replaced double quotes with single quotes of svg image but still no joy
```javascript
new_img = svg_img.replace(/"/g, '\'');
$("#qrdiv").html('<a href="http://www.gizmo.com/link/" target="_blank"><img src="'+new_img+'" /></a>');
```
The error is
<pre>Failed to load resource: net::ERR_FILE_NOT_FOUND</pre>

**Comment by kevkha** [comment]
I am using this http://davidshimjs.github.io/qrcodejs/ instead

**Comment by alexeyten** [comment]
`imageSync` returns image. To use it in src, you should encode it to base64 and use `data:` protocol.
Or don't use `<img>` and just put SVG-image as it is.

Anyway, it has nothing to do with qr-image.

**Comment by kevkha** [comment]
@alexeyten, thanks for your reply. I opted to use your latter suggestion (SVG-image as it) and it works like a champ. Thanks man.
