### ISSUE TITLE
# not supported

### ISSUE THREAD

**Issue by yedf** [alexeyten/qr-image#25]
I use this library to generate a qr code for a url with '#', but resulting qr code not include '#' and after

**Comment by alexeyten** [comment]
How did you do that and how did you checked?

Works here:
![QR image](https://disk.yandex.net/qr/?text=https%3A%2F%2Fgithub.com%2Falexeyten%2Fqr-image%2Fblob%2Fmaster%2Flib%2Ferrorcode.js%23L65&clean=1)

**Comment by yedf** [comment]
sorry, a bug in my own code.

**Comment by alexeyten** [comment]
That's OK.
