### ISSUE TITLE
Can't set image width and height？

### ISSUE THREAD

**Issue by 953133667** [alexeyten/qr-image#27]
This is my code:
(My system is win7)

```
var qr = require('qr-image');

var png_string = qr.imageSync("http://www.google.com/");
 fs.writeFile("e:/qrcodes/"+data[i].name+".png", png_string, 'utf8');
```
------------------------------------------------------------------------
Default ,Createed images width and height is 225 pixel. I need width and height is 2000 pixel.
Please help me ,Thx !

**Comment by alexeyten** [comment]
There is no options for image size, only for “module” (one square) size.
Image size obviously depends on size of text you want to encode. You could try to set module size to something big (e.g. `qr.imageSync("http://www.google.com/", {size: 44});`).

But actually, I don't see any reason to generate image so huge. May be you should use SVG? It will perfectly scale to any size you want.

**Comment by 953133667** [comment]
OK ,Thx !
