### ISSUE TITLE
Hi, question about png_sync 

### ISSUE THREAD

**Issue by dubiao** [alexeyten/qr-image#28]
I'm using "customize" option to make a logo into the qr.

I found there is a function in `png.png_sync(bitmap)` can convert the` bitmap` to `png` buffer.
But I didn't find a function that revert a `png` buffer to `bitmap` buffer.

Could you help me ?

**Comment by dubiao** [comment]
`function bitmap(matrix, size, margin)` can only convert a matrix to bitmap.

I have changed the qr image (added a logo) in customize function, and need modify the bitmap param as a result.

**Comment by alexeyten** [comment]
Why do you need such function? That would be PNG-image parser and I don't need it in QR-generating module.

You could use any of https://www.npmjs.com/search?q=png package that satisfy your needs.

**Comment by dubiao** [comment]
@alexeyten following my code snippet
```javacript
var qr = require('qr-image');
var qrCodeRes = qr.image(qrString, {type: "png", customize: function (bitmap) {
      var png = require('qr-image/lib/png');
      var images = require("images")  //a module images can draw image

      var qrBuffer = png.png_sync(bitmap)
      var qr = images(qrBuffer)
      var logo = images('./public/images/logo_for_qr.png')
      logo.size(30)
      qr.size(300)
      qr.draw(logo, 135, 135)
      // qr.save("kkk.png") //  This line can save qr-image whit a logo perfectly

      var buffer = qr.encode("png") //a module images function return a png buffer
      //
      // Isn't it needed do some convert with buffer and execute buffer.copy(bitmap.data) to change bitmap?
    }})
qrCodeRes.pipe(res) // I want out put the qr-image that returned by customize, is that possible that the qrCodeRes is the qr-image with my logo?
```

I know that I can simply save the changed qr-png as "kkk.png" and out put the kkk.png as result. I just wonder that is it possible to change the qrCodeRes to qr-image with logo.

**Comment by alexeyten** [comment]
Why you want to use `customize` here. You've got `images`, let it do everything for you.

I would write something like this:

```js
var qr = images(qr.imageSync(qrString));
qr.size(300);
qr.draw(logo, 135, 135);
var qrBuffer = qr.encode('png');

// Send result
res.end(qrBuffer);
```

**Comment by alexeyten** [comment]
`png_sync` is a “one-way” function. I don't need or want to implement PNG-parser, You've already got one in `images` module.
