### ISSUE TITLE
[Question] Optimize the size for better reading

### ISSUE THREAD

**Issue by J3rome** [alexeyten/qr-image#29]
Hi there,

First of all, thank you for this package, it work flawlessly!

I am trying to optimize the detection of a qr code. I already set the error correction to HIGH.

My QR code is pretty small (5 alphaNum characters). Id like to make the modules as big as possible to prevent bad reading.

I've done some research, my 5 alphaNum code can be stored in a Version 1 (21 modules x 21) QR Code with high correction level (can store up to 10 alphaNum characters).

My qrCode need to be 5.5cm by 5.5 cm. 
This mean that the module size should be 0.2619 cm (5.5 / 21 = 0.2619)

I am currently outputting my qrCode as pdf files. 
As stated in the doc, the size option only affect png & svg files.

Is there a way i can set my module size to 0.2619 cm ? (Or it equivalent in px with the good dpi)

Can i do it with pdf files ? Do i need to switch to another format ? (I hope not, would be way easier with pdf files but if i can't, i'll find a solution)

Also, i'm pretty sure it's not but it's worth asking : Is it possible to reduce the number of modules (say 15 modules x 15) in order to make the individual module bigger ?

Thanks a lot in advance !

**Comment by alexeyten** [comment]
Version 1 (21×21 modules) is smallest possible QR code. If you need smaller, you could look at [Data Matrix](https://en.wikipedia.org/wiki/Data_Matrix).

PDF (and other vector formats) are vector, it means you could scale it to whatever size you want.
Currently module size in PDF is 0.125in ≈ 0.32cm
