### ISSUE TITLE
parse url http://aaa.com/?env=test/#/consultant-form to http://aaa.com/?env=test/

### ISSUE THREAD

**Issue by jerrwy** [alexeyten/qr-image#40]
the #/consultant-form in url will lost

**Comment by alexeyten** [comment]
Sorry, what the question?

**Comment by jerrwy** [comment]
the string behind # in url will lost

**Comment by alexeyten** [comment]
How is it relevant to qr-code?

BTW, you should know, that browsers never send hash part (`#whatever`) to server.

**Comment by alexeyten** [comment]
If `#` is a part of query parameter, it should be properly encoded, so you url should be `http://aaa.com/?env=test/%23/consultant-form`

**Comment by jerrwy** [comment]
thx.. i know the reason.
