### ISSUE TITLE
Add text below or above QR-image

### ISSUE THREAD

**Issue by heker121** [alexeyten/qr-image#49]
Hello I'm working on webapp for our company and i was asked to create QR Code generator with text above or below Code. Is tthere any way to add this texts in to image? 

![temppng00](https://user-images.githubusercontent.com/11874512/41899610-2c72b818-792d-11e8-8a3c-24f5c13d3f3d.png)

**Comment by alexeyten** [comment]
That's a Data Matrix on your picture, not a QR Code.
Anyway, it's just an image so you could use any image manipulating tool to add text.
